name: Debug

on: [push]

jobs:
  debug:
    runs-on: ubuntu-20.04
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Debug environment
      run: |
        echo "=== SYSTEM INFO ==="
        uname -a
        echo "=== PYTHON VERSIONS ==="
        which python3
        python3 --version
        echo "=== WORKING DIRECTORY ==="
        pwd
        ls -la
        echo "=== PYTHON PATH ==="
        python3 -c "import sys; print('\\n'.join(sys.path))"
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
        
    - name: Upgrade pip and install minimal deps
      run: |
        python -m pip install --upgrade pip
        pip install Flask==2.3.3
        pip list
        
    - name: Test basic Python execution
      run: |
        python -c "print('Python works')"
        python -c "import Flask; print('Flask works')"
        
    - name: Try to import app with minimal setup
      run: |
        export SECRET_KEY=test_key
        export FLASK_ENV=testing
        export TESTING=true
        python -c "
import os
print('Environment variables:')
for k, v in os.environ.items():
    if 'FLASK' in k or 'SECRET' in k or 'TESTING' in k:
        print(f'  {k}={v}')

print('\\nTrying to import app...')
try:
    import app
    print('SUCCESS: app imported!')
except Exception as e:
    print(f'FAILED: {e}')
    import traceback
    traceback.print_exc()
"