name: Incremental

on: [push]

jobs:
  incremental:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Step 1 - Install pip
      run: |
        python -m pip install --upgrade pip
        echo "✅ Step 1 complete"
    
    - name: Step 2 - Install Flask only
      run: |
        pip install Flask==2.3.3
        echo "✅ Step 2 complete"
    
    - name: Step 3 - Test Flask import
      run: |
        python -c "import flask; print('Flask version:', flask.__version__)"
        echo "✅ Step 3 complete"
    
    - name: Step 4 - Install authlib
      run: |
        pip install authlib==1.2.1
        python -c "import authlib; print('Authlib imported')"
        echo "✅ Step 4 complete"
    
    - name: Step 5 - Install pymongo
      run: |
        pip install pymongo==4.6.0
        python -c "import pymongo; print('PyMongo imported')"
        echo "✅ Step 5 complete"
    
    - name: Step 6 - Install remaining deps
      run: |
        pip install python-dotenv==1.0.0 flask-mail==0.9.1 requests==2.31.0
        echo "✅ Step 6 complete"
    
    - name: Step 7 - Set basic env vars
      run: |
        export SECRET_KEY=test_key
        export FLASK_ENV=testing
        python -c "import os; print('SECRET_KEY:', os.getenv('SECRET_KEY', 'NOT_SET'))"
        echo "✅ Step 7 complete"
    
    - name: Step 8 - Try importing database module
      run: |
        export SECRET_KEY=test_key
        export FLASK_ENV=testing
        export TESTING=true
        python -c "
import sys
import os
print('Python path:', sys.path[0])
print('Files in current dir:', [f for f in os.listdir('.') if f.endswith('.py')][:5])
try:
    import database
    print('✅ Database module imported')
except Exception as e:
    print('❌ Database import failed:', e)
    import traceback
    traceback.print_exc()
"
        echo "✅ Step 8 complete"
    
    - name: Step 9 - Try importing models module
      run: |
        export SECRET_KEY=test_key
        export FLASK_ENV=testing
        export TESTING=true
        python -c "
try:
    import models
    print('✅ Models module imported')
except Exception as e:
    print('❌ Models import failed:', e)
    import traceback
    traceback.print_exc()
"
        echo "✅ Step 9 complete"
    
    - name: Step 10 - Try importing auth module
      run: |
        export SECRET_KEY=test_key
        export FLASK_ENV=testing
        export TESTING=true
        export GOOGLE_CLIENT_ID=placeholder
        export GOOGLE_CLIENT_SECRET=placeholder
        python -c "
try:
    import auth
    print('✅ Auth module imported')
except Exception as e:
    print('❌ Auth import failed:', e)
    import traceback
    traceback.print_exc()
"
        echo "✅ Step 10 complete"
    
    - name: Step 11 - Try importing app module
      run: |
        export SECRET_KEY=test_key
        export FLASK_ENV=testing
        export TESTING=true
        export GOOGLE_CLIENT_ID=placeholder
        export GOOGLE_CLIENT_SECRET=placeholder
        python -c "
try:
    import app
    print('✅ App module imported successfully!')
    print('Flask app created:', hasattr(app, 'app'))
except Exception as e:
    print('❌ App import failed:', e)
    import traceback
    traceback.print_exc()
"
        echo "✅ Step 11 complete - ALL IMPORTS SUCCESSFUL!"