name: No Coverage Test

on:
  push:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set environment
      run: |
        echo "SECRET_KEY=test_secret_key" >> $GITHUB_ENV
        echo "FLASK_ENV=testing" >> $GITHUB_ENV
        echo "TESTING=true" >> $GITHUB_ENV
        echo "CI=true" >> $GITHUB_ENV
        echo "GOOGLE_CLIENT_ID=placeholder_client_id" >> $GITHUB_ENV
        echo "GOOGLE_CLIENT_SECRET=placeholder_client_secret" >> $GITHUB_ENV

    - name: Test imports
      run: |
        python -c "import app; import auth; import database; import models; print('✅ All imports successful')"

    - name: Run basic CI tests only
      run: |
        python -m pytest tests/test_ci_basic.py -v

    - name: Run all tests without coverage
      run: |
        python -m pytest tests/ -v --tb=short